server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/malintha9/cloud-config/tree/main/mem-service
          search-paths:
           - '*service'



